Repository geertmeersman/telenet, pull requests merged in 2023-05, with the labels that each got.

#124 Merged into HACS :-)
  README.md
Labels: documentation, patch

#125 Merged into HACS Default :-)
  README.md
Labels: documentation, patch

#126 Merged into HACS Default :-)
  README.md
Labels: documentation, patch

#130 Bypass wireless setting when 500 error is returned (meaning no wirele…
  custom_components/telenet/client.py
  custom_components/telenet/config_flow.py
Labels: fix, patch

#131 chore: fix spelling
  README.md
  custom_components/telenet/client.py
Labels: documentation, patch

#133 Config flow: Remove email validator & language choice improvement
  custom_components/telenet/config_flow.py
  custom_components/telenet/translations/en.json
  custom_components/telenet/translations/nl.json
Labels: enhancement, patch

#134 Config flow improvement for language option
  README.md
  custom_components/telenet/config_flow.py
  images/screenshots/api_v1.png
Labels: enhancement, patch

#136 Lovelace markdown example fix
  README.md
Labels: documentation, patch

#137 Lovelace markdown example fix
  README.md
Labels: documentation, patch

#138 Readme improvement
  README.md
Labels: documentation, patch

#141 Include usage sensors when no modem is available,references #139
  custom_components/telenet/client.py
Labels: fix, patch

#142 Adapt daily usage for CAP Internet category
  custom_components/telenet/client.py
Labels: fix, patch

#144 Mobile only / No children fix, fixes #140
  custom_components/telenet/client.py
Labels: fix, patch

#148 Correcting Telenet lastUpdate, adding timezone +0200, references #147
  custom_components/telenet/client.py
  custom_components/telenet/entity.py
Labels: fix, patch

#149 New sensors: customer, mailboxes, simdetails, modem advanced info
  custom_components/telenet/__init__.py
  custom_components/telenet/client.py
  custom_components/telenet/config_flow.py
  custom_components/telenet/const.py
  custom_components/telenet/entity.py
  custom_components/telenet/models.py
  custom_components/telenet/sensor.py
  custom_components/telenet/utils.py
Labels: enhancement, patch

#152 Decrease connection timeout to 3 seconds
  .github/workflows/bump_version_and_release.yml
  custom_components/telenet/const.py
Labels: enhancement, patch

#154 Ignore advanced modem settings if no access, fixes #153
  custom_components/telenet/client.py
  custom_components/telenet/const.py
  custom_components/telenet/models.py
Labels: fix, patch

#155 Fix API endpoint
  custom_components/telenet/client.py
Labels: fix, patch

#157 Telenet V1 API Support
  custom_components/telenet/client.py
Labels: enhancement, patch

#158 V1 API: DTV & invoices
  README.md
  custom_components/telenet/client.py
Labels: enhancement, patch

#159 V1 API: Off peak usage & total usage added
  custom_components/telenet/client.py
Labels: enhancement, patch

#160 V1 API: Total usage included offpeak usage
  custom_components/telenet/client.py
Labels: fix, patch

#161 str_to_float function fix
  custom_components/telenet/utils.py
Labels: fix, patch

#163 Ignore Error 500
  custom_components/telenet/client.py
Labels: enhancement, patch

#164 Fix if product.product_subscription_info is None
  custom_components/telenet/client.py
Labels: fix, patch

#165 fix: Restore offpeak usage
  custom_components/telenet/client.py
Labels: fix, patch
