Repository geertmeersman/telenet, pull requests merged in 2023-04, with the labels that each got.

#81 fix: sensor name, added address, translations, flow label improved
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/dependabot.yml
  .github/pre-commit-config.yaml
  .github/workflows/hacs.yml
  .github/workflows/hassfest.yml
  .github/workflows/lint.yml
  .github/workflows/validate.yml
  .ruff.toml
  CHANGELOG.md
  CODE_OF_CONDUCT.md
  README.md
  custom_components/__init__.py
  custom_components/telenet/__init__.py
  custom_components/telenet/client.py
  custom_components/telenet/config_flow.py
  custom_components/telenet/manifest.json
  custom_components/telenet/models.py
  custom_components/telenet/sensor.py
  custom_components/telenet/translations/en.json
  custom_components/telenet/translations/nl.json
  custom_components/telenet/utils.py
  requirements.txt
  tests/__init__.py
  tests/bandit.yaml
  tests/test_init.py
Labels: documentation, enhancement, major, breaking

#80 feat: Create bandit.yml
  .github/workflows/bandit.yml
Labels: patch

#79 feat: Create dependency-review.yml
  .github/workflows/dependency-review.yml
Labels: enhancement, patch, feature

#84 fix: address id none
  custom_components/telenet/client.py
Labels: bug, patch

#85 fix: Entity id aligned with sensor name
  custom_components/telenet/entity.py
Labels: bug, enhancement, patch

#86 fix: import format_entity_name
  .github/workflows/codeql.yml
  custom_components/telenet/entity.py
Labels: bug, patch

#87 fix: sensor name without entity id
  custom_components/telenet/client.py
Labels: enhancement, patch

#88 fix: README.md
  README.md
Labels: documentation, patch

#89 feat: Peak and off-peak usage attributes as separate list in attributes and language fix
  README.md
  custom_components/telenet/__init__.py
  custom_components/telenet/client.py
  custom_components/telenet/const.py
  images/screenshots/lovelace_peak_offpeak.png
Labels: bug, documentation, patch, feature

#90 fix: Renamed sensor.telenet_internet_internet_usage to sensor.telenet_internet_usage
  custom_components/telenet/client.py
Labels: enhancement, patch

#91 feat: Update README.md
  README.md
Labels: documentation, patch

#92 fix: Update README.md
  README.md
Labels: documentation, patch

#93 Update README.md
  README.md
Labels: documentation, patch

#94 fix: Update README.md
  README.md
Labels: documentation, patch

#95 Catch Telenet ocapi errors
  .github/workflows/pr-checker.yml
  .ruff.toml
  custom_components/telenet/client.py
Labels: bug, enhancement, minor

#96 Add sales price
  .github/dependabot.yml
  .github/workflows/bandit.yml
  .github/workflows/codeql.yml
  .github/workflows/dependency-review.yml
  .github/workflows/lint.yml
  .github/workflows/validate.yml
  CHANGELOG.md
  README.md
  custom_components/telenet/__init__.py
  custom_components/telenet/client.py
  custom_components/telenet/entity.py
  custom_components/telenet/models.py
  custom_components/telenet/utils.py
Labels: enhancement, patch

#99 Device refactor, sensor names changed, customer info, product prices …
  CHANGELOG.md
  README.md
  custom_components/telenet/__init__.py
  custom_components/telenet/client.py
  custom_components/telenet/const.py
  custom_components/telenet/entity.py
  custom_components/telenet/models.py
  custom_components/telenet/sensor.py
  images/screenshots/lovelace_peak_offpeak.png
Labels: enhancement, major, breaking

#100 Fix update with override
  custom_components/telenet/entity.py
Labels: enhancement, patch

#101 Readme addition for dual gauge
  README.md
Labels: documentation, patch

#102 Update README.md - Discord server added
  README.md
Labels: documentation, patch

#104 Fix error message in config flow
  .github/labels.yml
  custom_components/telenet/config_flow.py
Labels: bug, patch

#105 Indentation correction
  custom_components/telenet/config_flow.py
Labels: bug, patch

#106 CODEOWNERS file added
  .github/CODEOWNERS
Labels: enhancement, patch

#107 Update README.md
  README.md
Labels: documentation, patch

#108 Update README.md
  README.md
Labels: documentation, patch

#111 Doc update
  .github/PULL_REQUEST_TEMPLATE.md
  .github/labels.yml
  README.md
Labels: documentation, patch

#113 Workaround 500 bug daily usage, fixes #112
  .pre-commit-config.yaml
  custom_components/telenet/client.py
Labels: fix, patch

#114 Workaround 500 bug daily usage, fixes #112
  custom_components/telenet/client.py
Labels: fix, patch

#115 Update README.md
  README.md
Labels: documentation, patch

#116 Update bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, patch

#121 Catch product error, fixes #120
  custom_components/telenet/__init__.py
Labels: fix, patch

#122 Raise TelenetServiceException when no products are found
  README.md
  custom_components/telenet/client.py
Labels: enhancement, patch
