Repository geertmeersman/telenet, pull requests merged in 2023-06, with the labels that each got.

#171 fix: Improved debug
  .github/labels.yml
  .github/scripts/get_new_version.py
  .github/scripts/pr_extract_labels.py
  .github/workflows/pr-checker.yml
  .pre-commit-config.yaml
  .ruff.toml
  custom_components/telenet/__init__.py
  custom_components/telenet/client.py
Labels: fix, patch, refactor

#172 fix: pass HTTP 500 responses for product usage
  .ruff.toml
  custom_components/telenet/client.py
Labels: fix, patch

#173 fix: Bypass billcycles on 500 for specific products
  custom_components/telenet/client.py
Labels: fix, patch

#174 fix: Bypass billcycles on 500 for specific products
  custom_components/telenet/client.py
Labels: fix, patch

#175 docs: improved lovelace example for network clients
  README.md
Labels: patch, docs

#176 V1 API: Fix multiple modems
  custom_components/telenet/client.py
Labels: fix, patch

#177 fix: throw Telenet service exception when http > 404 during login
  .github/release-drafter-beta.yml
  .github/scripts/get_new_version.py
  .github/workflows/bump_version_and_prerelease.yml
  custom_components/telenet/client.py
Labels: fix, patch

#178 docs: TOC & Troubleshooting
  README.md
  images/screenshots/disable-debug-logging.gif
  images/screenshots/enable-debug-logging.gif
Labels: patch, docs

#180 fix: create_extra_attributes_list
  custom_components/telenet/client.py
Labels: fix, patch

#183 Create FUNDING.yml
  .github/FUNDING.yml
Labels: patch

#187 fix: V1 check if peak usage is present
  .github/release-drafter.yml
  .github/workflows/bandit.yml
  .github/workflows/bump_version_and_prerelease.yml
  .github/workflows/bump_version_and_release.yml
  .github/workflows/codeql.yml
  .github/workflows/dependency-review.yml
  .github/workflows/lint.yml
  .github/workflows/pr-checker.yml
  .github/workflows/stale.yaml
  .github/workflows/synchronize-labels.yml
  .github/workflows/validate.yml
  VERSION
  custom_components/telenet/client.py
  custom_components/telenet/const.py
  custom_components/telenet/manifest.json
Labels: fix, patch, refactor
